"""Nueva Migracion

Revision ID: 8cd41d500501
Revises: e7f3afdf37a1
Create Date: 2024-10-17 22:09:33.646853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd41d500501'
down_revision = 'e7f3afdf37a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre123', sa.String(length=100), nullable=False))
        batch_op.drop_constraint('empresa_nombre_key', type_='unique')
        batch_op.create_unique_constraint(None, ['nombre123'])
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('empresa_nombre_key', ['nombre'])
        batch_op.drop_column('nombre123')

    # ### end Alembic commands ###
