"""Ajuste Migracion

Revision ID: 9243206ac362
Revises: 0c4251b57cbc
Create Date: 2024-10-19 14:55:33.396630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9243206ac362'
down_revision = '0c4251b57cbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuente', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidente', schema=None) as batch_op:
        batch_op.drop_column('fuente')

    # ### end Alembic commands ###
