"""Actualizacion Tabla Incidente

Revision ID: d449680a4ada
Revises: 9243206ac362
Create Date: 2024-10-19 19:54:28.805369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd449680a4ada'
down_revision = '9243206ac362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_modificacion', sa.DateTime(), nullable=True))
        batch_op.alter_column('fuente',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidente', schema=None) as batch_op:
        batch_op.alter_column('fuente',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('fecha_modificacion')

    # ### end Alembic commands ###
